apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: social-scheduler

resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - scheduler-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: social-scheduler
