apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patchesStrategicMerge:
  - replicas-patch.yaml

configMapGenerator:
  - name: social-scheduler-config
    behavior: merge
    literals:
      - NODE_ENV=production
